# This viminfo file was generated by Vim 8.2.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h

# Registers:
"a	CHAR	0
	YUKARI
|3,2,10,0,1,0,1633823436,"Iyukari:jjj"

"x	CHAR	0
	MAKI
|3,0,33,0,1,0,1633828744,"Imaki:jjj"
