# This viminfo file was generated by Vim 8.2.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h

# Registers:
"a 	CHAR	0
	Iyukari:jjj
|3,2,10,0,1,0,1633823436,"Iyukari:jjoqkbjj"

"b	CHAR	0
	Imaki:jjj
|3,0,11,0,1,0,1633823711,"Imaki:jjj"
"g	LINE	0
	uooooooooo
|3,0,16,1,1,0,1633824555,"uooooooooo"
